### ISSUE TITLE
fatal error: 'EXTERN.h' file not found  [SOLVED]

### ISSUE THREAD

**Issue by DabeDotCom** [chansen/p5-Mac-SystemDirectory#1]
Trying to build this on recent versions of macOS, I was running into the dreaded:

```
prompt% perl Makefile.PL 
HASCOMPILERkmMa/TESTk0pi.c:2:10: fatal error: 'EXTERN.h' file not found
#include "EXTERN.h"
         ^~~~~~~~~~
1 error generated.
Couldn't execute cc  -g -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -Os "-I/System/Library/Perl/5.30/darwin-thread-multi-2level/CORE"   -c HASCOMPILERkmMa/TESTk0pi.c -o HASCOMPILERkmMa/TESTk0pi.o: Inappropriate ioctl for device at Makefile.PL line 14.
Requires a compiler
```

Eventually, I stumbled upon the idea of fetching the latest [ExtUtils/HasCompiler.pm](https://github.com/Leont/extutils-hascompiler) and manually replacing the version in `inc/`...

Much to my delight (and surprise) it actually built!  😅  [Albeit with a bunch of `compound-token-split-by-macro`, `extra-tokens`, and `switch` warnings, but hey, I'm not complaining...  «grin»]

At any rate, whenever somebody gets a chance, I might suggest cutting a `0.14` release that pulls in the latest `ExtUtils::HasCompiler` — currently version 0.023.

Thanks!  :-D

**Comment by karenetheridge** [comment]
Interesting, I wonder why I never got any cpantesters reports with this error..

I've had no problems beacuse I'm way back on Catalina still.

**Comment by karenetheridge** [comment]
new version released!
